version: '3.8'
services:
  authapi-app:
    build: .
    container_name: AuthApi
    restart: always
    depends_on:
      - db
    networks:
      - app-network

  nginx:
    image: nginx:1.25.3
    container_name: authapi-nginx
    ports:
      - "81:80"
    depends_on:
      - authapi-app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app-network

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql_db
    environment:
      SA_PASSWORD: "Ke123456"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mssql_data:
