USE [master]
GO
/****** Object:  Database [authapi]    Script Date: 31.01.2024 10:51:39 ******/
CREATE DATABASE [authapi]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'authapi', FILENAME = N'/var/opt/mssql/data/authapi.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'authapi_log', FILENAME = N'/var/opt/mssql/data/authapi_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [authapi] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [authapi].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [authapi] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [authapi] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [authapi] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [authapi] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [authapi] SET ARITHABORT OFF 
GO
ALTER DATABASE [authapi] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [authapi] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [authapi] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [authapi] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [authapi] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [authapi] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [authapi] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [authapi] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [authapi] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [authapi] SET  DISABLE_BROKER 
GO
ALTER DATABASE [authapi] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [authapi] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [authapi] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [authapi] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [authapi] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [authapi] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [authapi] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [authapi] SET RECOVERY FULL 
GO
ALTER DATABASE [authapi] SET  MULTI_USER 
GO
ALTER DATABASE [authapi] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [authapi] SET DB_CHAINING OFF 
GO
ALTER DATABASE [authapi] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [authapi] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [authapi] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [authapi] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'authapi', N'ON'
GO
ALTER DATABASE [authapi] SET QUERY_STORE = OFF
GO
USE [authapi]
GO
/****** Object:  Table [dbo].[apps]    Script Date: 31.01.2024 10:51:39 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[apps](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[appname] [varchar](255) NULL,
	[secretkey] [varchar](255) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[permission_zuordnung]    Script Date: 31.01.2024 10:51:39 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[permission_zuordnung](
	[id] [int] NULL,
	[windows_kennung] [varchar](255) NULL,
	[permission_id] [int] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[permissions]    Script Date: 31.01.2024 10:51:39 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[permissions](
	[id] [int] NULL,
	[permission] [varchar](255) NULL,
	[app_id] [int] NULL
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [authapi] SET  READ_WRITE 
GO
